### ISSUE TITLE
it might be a typo

### ISSUE THREAD

**Issue by ohkimchi** [bvanderlaan/swagger-ui-restify#2]
There are some countries in the world using "custome" instead of "custom". And I was having errors when applying this library and then realise that in index.js there are instead of "customSiteTitle", there are "custom**e**SiteTitle". I would be glad if this bit of information is helpful to anyone seeing this issue.

**Comment by bvanderlaan** [comment]
I never noticed that when I forked the project; probably as it looks to only be `customeSiteTitle` internally  and all external APIs are expecting `customSiteTitle`. Not sure how it caused you issues but it is inconsistent to say the least. I fixed the type-o here (8b68ccdef680fdc47665f9a7c8831431b09747b0) and will get it in the next release.

Sorry for the very very late response I changed jobs at the top of the year and am back to doing C++ work so I let my Node.js projects slide while I was ramping back up on the latest in C++. I'll try to be more responsive going forward.
